version: '3.8'

services:
  next:
    image: node:18.17
    working_dir: /var/www/html
    ports:
      - '3000:3000'
    command: bash -c "npm i && npm run dev"
    volumes:
      - '.:/var/www/html'
